### ISSUE TITLE
entity_id filter in the "events:states" node does not work

### ISSUE THREAD

**Issue by ycardon** [AYapejian/node-red-contrib-home-assistant#1]
Hello, nice jobs you've done !

The entity_id filter in the "events:states" node does not work for me (it does not filter anything).

The problem seems to be in "node-server-state-changed.js" lines 59: it does not extract the entity_id but the event_type.

for instance in the Node-RED debug pane, I get:
```
object
  event_type: "state_changed"
  topic: "state_changed" <-- should be "sun.sun" according to line 61
  payload: object
    event_type: "state_changed"
    entity_id: "sun.sun"

```

and later in line 66, you're using the same wrong value ("state_changed" instead of "sun.sun") to match the filter and blacklist.

**Comment by AYapejian** [comment]
Thanks.  Yea,  I thought I'd have more time to clean certain things up when I started this unfortunately work has consumed most of my free time since.  I do plan on getting an update out with fixes and some additional features but can't make a guess at when that'll be yet.  Thanks for the report.

**Comment by ycardon** [comment]
When you'll find some time for, I'll be happy to test your release ^^

**Comment by AYapejian** [comment]
Hey so looking at this I think I dealt with it a long while ago.  Look at the `dev-master` branch.  You should be able to just `npm install AYapejian/node-red-contrib-home-assistant#dev-master` probably have to remove the official one from node-red install, not sure.   Fair warning, I can't even remember how much I've changed since the version on master, if you go on with the testing I'd suggest creating a new flows file to test with as the current flows probably wouldn't work.
