### ISSUE TITLE
Home assistant connection failed - can't figure out why

### ISSUE THREAD

**Issue by sebk-666** [AYapejian/node-red-contrib-home-assistant#83]
Hi,
I'm running the node-red:v8 Docker image.
HA is also running as Docker container on the same host.
I configured the HA server in node-red als `http://192.168.x.x:8123` and provided the correct api password (copy&paste from HA's secrets.yaml file).
Still I'm getting this error every 2 seconds in the node-red container's log:
```
[error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://192.168.x.x:8123/ <password redacted>
```
I opened a shell on the node-red container, tried a `curl http://192.168.x.x:8123/` and got a response that looked like the HA login screen:
```
$ curl http://192.168.x.x:8123/
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Home Assistant</title>
[...]
```

So this looks to me like it should be working.
What am I missing?

Sebastian

**Comment by JonLaliberte** [comment]
I'm not sure, but...
I assume you've tried restarting the node-red container?
Is there more than one home assistant server configured? You can check this by going to the hamburger menu and going to Configuration nodes. Then in "On all flows" there should only be one Home Assistant entry.

**Comment by sebk-666** [comment]
Hm, I restarted the container multiple times in the course of several days, because after every config change I tried unsuccessfully, I shut down the container so the annoying log messages wouldn't eat my disk space.
I just started the container again and suddenly it seems to work. WTF?!
I feel stupid now... :-(

Thanks anyway!

Sebastian

**Comment by JonLaliberte** [comment]
@sebk-666 Hah, it's no problem. I ran in to a lot of similar issues when I was first getting NR set up. I also noticed at some point after importing some flows from someone else that I had a "stuck" server config which only went away after deleting the config and restarting NR (otherwise it kept spamming the logs like you noticed). You probably fixed some other networking issue at some point after your last restart of the container, so you were able to reach the HA container/instance but NR still needed to reset. It could also just be random luck 🤷🏼‍♂️
